DROP TABLE IF EXISTS car_inventory;

CREATE TABLE car_inventory (
  inventory_id SERIAL PRIMARY KEY,
  year INT NOT NULL,
  make VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  color VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  sold BOOL NOT NULL
);

INSERT INTO car_inventory (year, make, model, color, description, sold)
VALUES (1990, 'Ford', 'Bronco II', 'Puce', 'tertiary', true),
  (2005, 'Dodge', 'Ram 2500', 'Aquamarine', 'Stand-alone', true),
  (1985, 'Mazda', 'RX-7', 'Teal', 'middleware', true),
  (1996, 'Porsche', '911', 'Goldenrod', 'architecture', true),
  (1993, 'Mercedes-Benz', '500SEL', 'Pink', 'core', true),
  (2000, 'Plymouth', 'Voyager', 'Goldenrod', 'next generation', true),
  (1988, 'Acura', 'Integra', 'Puce', 'Optional', false),
  (2004, 'Volvo', 'S80', 'Crimson', 'Vision-oriented', true),
  (2001, 'BMW', '530', 'Puce', 'Total', true),
  (2002, 'Chevrolet', 'Express 1500', 'Blue', 'Future-proofed', false),
  (2003, 'Cadillac', 'Escalade EXT', 'Khaki', 'discrete', true),
  (1992, 'Pontiac', 'Firebird', 'Puce', 'intangible', false),
  (2001, 'Toyota', 'Camry', 'Purple', 'optimal', false),
  (1994, 'Land Rover', 'Defender 90', 'Orange', 'responsive', true),
  (1992, 'Infiniti', 'Q', 'Aquamarine', 'Fundamental', false),
  (1994, 'Suzuki', 'Swift', 'Blue', 'middleware', false),
  (1991, 'Pontiac', 'Grand Prix', 'Maroon', 'composite', false),
  (2007, 'BMW', 'Z4 M', 'Crimson', 'Diverse', true),
  (2009, 'Hyundai', 'Azera', 'Red', 'artificial intelligence', true),
  (2002, 'Lexus', 'LX', 'Khaki', 'complexity', false),
  (2004, 'Hummer', 'H2', 'Orange', 'bandwidth-monitored', true),
  (2011, 'Chevrolet', 'Equinox', 'Yellow', 'focus group', true),
  (2006, 'Suzuki', 'XL-7', 'Red', 'system engine', true),
  (2004, 'Chevrolet', 'Silverado 1500', 'Green', 'high-level', false),
  (2002, 'Ford', 'Th!nk', 'Turquoise', 'workforce', true),
  (2002, 'Lexus', 'SC', 'Yellow', 'responsive', false),
  (2006, 'Jeep', 'Commander', 'Teal', 'Focused', true),
  (2013, 'Subaru', 'BRZ', 'Pink', 'Synergistic', true),
  (2000, 'Ford', 'Windstar', 'Purple', 'matrix', true),
  (1993, 'Ford', 'Festiva', 'Maroon', 'Open-architected', false),
  (1992, 'GMC', 'Sonoma Club', 'Pink', 'Multi-channelled', true),
  (2009, 'Nissan', 'Cube', 'Goldenrod', 'hub', true),
  (1988, 'Ford', 'Taurus', 'Violet', 'Object-based', true),
  (2010, 'Jaguar', 'XF', 'Red', 'Ergonomic', true),
  (2011, 'Suzuki', 'Kizashi', 'Pink', 'core', true),
  (1997, 'Mazda', '626', 'Red', 'real-time', false),
  (1998, 'Oldsmobile', 'Cutlass', 'Aquamarine', 'Re-engineered', false),
  (1987, 'Mitsubishi', 'Cordia', 'Turquoise', 'multi-tasking', false),
  (2007, 'Maybach', '57', 'Teal', 'impactful', true),
  (1999, 'Lexus', 'ES', 'Turquoise', 'explicit', true),
  (2007, 'Porsche', '911', 'Violet', 'utilisation', true),
  (1992, 'Mercedes-Benz', '300SL', 'Blue', 'Graphic Interface', false),
  (1994, 'Honda', 'Accord', 'Maroon', 'complexity', true),
  (2010, 'Volkswagen', 'Rabbit', 'Purple', 'asymmetric', false),
  (2011, 'MINI', 'Countryman', 'Maroon', 'initiative', false),
  (1990, 'Ford', 'Aerostar', 'Crimson', 'capability', true),
  (2006, 'Chevrolet', 'Silverado 3500HD', 'Blue', 'encoding', true),
  (1996, 'Nissan', '240SX', 'Puce', 'tangible', true),
  (2005, 'Volkswagen', 'Passat', 'Turquoise', 'client-server', true),
  (1996, 'Isuzu', 'Hombre', 'Goldenrod', 'impactful', true),
  (2009, 'Lexus', 'LS', 'Maroon', 'neural-net', true),
  (2012, 'Lexus', 'CT', 'Crimson', 'initiative', true),
  (2008, 'Ford', 'Fusion', 'Yellow', 'upward-trending', false),
  (1986, 'Pontiac', 'Firefly', 'Khaki', 'internet solution', false),
  (2006, 'Honda', 'Civic', 'Maroon', 'Customizable', false),
  (2006, 'Mercedes-Benz', 'CLS-Class', 'Crimson', 'Cross-group', true),
  (2000, 'Buick', 'Park Avenue', 'Pink', 'hub', false),
  (2012, 'Aston Martin', 'V8 Vantage', 'Crimson', 'intangible', true),
  (2001, 'Pontiac', 'Bonneville', 'Goldenrod', 'Extended', true),
  (1995, 'Infiniti', 'Q', 'Aquamarine', 'Future-proofed', true),
  (1997, 'Chrysler', 'Town & Country', 'Maroon', 'adapter', false),
  (2012, 'Ram', 'C/V', 'Crimson', 'paradigm', false),
  (2000, 'Mazda', 'MX-5', 'Green', 'help-desk', false),
  (2001, 'Toyota', 'Celica', 'Pink', 'Digitized', true),
  (1993, 'Dodge', 'D350', 'Khaki', '6th generation', true),
  (2006, 'Mercedes-Benz', 'SL-Class', 'Green', 'neutral', false),
  (2006, 'Volkswagen', 'GTI', 'Fuscia', 'focus group', false),
  (2005, 'Acura', 'RSX', 'Khaki', 'Compatible', true),
  (2006, 'Panoz', 'Esperante', 'Aquamarine', 'local', true),
  (1995, 'GMC', '1500', 'Teal', 'Distributed', true),
  (2006, 'Lexus', 'SC', 'Goldenrod', 'secured line', true),
  (2007, 'Mercedes-Benz', 'CL-Class', 'Turquoise', 'well-modulated', true),
  (1993, 'Lotus', 'Esprit', 'Turquoise', 'initiative', true),
  (1993, 'Dodge', 'D350', 'Pink', 'local', true),
  (2002, 'Cadillac', 'Seville', 'Crimson', 'capability', true),
  (2004, 'Porsche', 'Boxster', 'Fuscia', 'frame', true),
  (1986, 'Subaru', 'Leone', 'Indigo', '3rd generation', false),
  (1999, 'Dodge', 'Ram 1500', 'Fuscia', 'Multi-layered', true),
  (1996, 'Holden', 'VS Commodore', 'Green', 'collaboration', true),
  (2005, 'Cadillac', 'SRX', 'Orange', 'data-warehouse', true),
  (2010, 'Mercedes-Benz', 'CLS-Class', 'Violet', 'needs-based', true),
  (2012, 'Hyundai', 'Santa Fe', 'Orange', 'Vision-oriented', true),
  (2012, 'Volkswagen', 'Passat', 'Green', 'Enhanced', true),
  (2011, 'Mazda', 'Miata MX-5', 'Pink', 'Multi-tiered', true),
  (2004, 'Nissan', 'Sentra', 'Mauv', 'Expanded', false),
  (2011, 'Chevrolet', 'Express 1500', 'Goldenrod', 'zero administration', false),
  (1992, 'Dodge', 'D250 Club', 'Pink', 'Stand-alone', false),
  (2008, 'Chevrolet', 'Malibu', 'Puce', 'high-level', true),
  (1988, 'Lincoln', 'Town Car', 'Aquamarine', 'Right-sized', true),
  (1996, 'Ford', 'Bronco', 'Blue', 'Multi-channelled', true),
  (2008, 'Honda', 'Civic', 'Blue', 'customer loyalty', false),
  (2007, 'Ford', 'E350', 'Green', 'conglomeration', true),
  (2004, 'Buick', 'Rainier', 'Teal', 'monitoring', false),
  (2009, 'Kia', 'Borrego', 'Crimson', 'fault-tolerant', true),
  (2009, 'Toyota', 'Camry Hybrid', 'Khaki', 'Organized', false),
  (1996, 'Mitsubishi', 'GTO', 'Indigo', 'toolset', false),
  (2011, 'Mazda', 'CX-7', 'Red', 'executive', false),
  (2003, 'Ford', 'Explorer', 'Khaki', 'standardization', false),
  (2011, 'Nissan', 'Quest', 'Mauv', 'Progressive', false),
  (2010, 'Kia', 'Sedona', 'Blue', 'Synchronised', true);